# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academics',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('gpa', models.FloatField(default=0.0)),
                ('weighted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Grader',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Nominator',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=10)),
                ('hispanic', models.BooleanField()),
                ('athletic', models.BooleanField()),
                ('arts', models.BooleanField()),
                ('stem', models.BooleanField()),
                ('community_service', models.BooleanField()),
                ('personal_statement', models.BooleanField()),
                ('resume', models.BooleanField()),
                ('transcript', models.BooleanField()),
            ],
        ),
    ]
