# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 04:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='STEM',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='academics',
            name='act_composite',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='academics',
            name='act_english',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='academics',
            name='act_math',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='academics',
            name='act_reading',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='academics',
            name='act_science',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='academics',
            name='act_writing',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='academics',
            name='class_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='academics',
            name='class_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='academics',
            name='sat_composite',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='academics',
            name='sat_math',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='academics',
            name='sat_reading',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='academics',
            name='sat_writing',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='birthday',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='student',
            name='county',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='district',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='school_name',
            field=models.CharField(default='null', max_length=300),
        ),
        migrations.AlterField(
            model_name='grader',
            name='category',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='grader',
            name='email',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='grader',
            name='first_name',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AlterField(
            model_name='grader',
            name='last_name',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AlterField(
            model_name='grader',
            name='phone',
            field=models.CharField(default='null', max_length=10),
        ),
        migrations.AlterField(
            model_name='nominator',
            name='email',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='nominator',
            name='first_name',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AlterField(
            model_name='nominator',
            name='last_name',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AlterField(
            model_name='nominator',
            name='phone',
            field=models.CharField(default='null', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='arts',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='athletic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='community_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='hispanic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='personal_statement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(default='null', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='resume',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='stem',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='transcript',
            field=models.BooleanField(default=False),
        ),
    ]
