# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 08:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0004_auto_20171104_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='nominator',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='nominations.Nominator'),
        ),
    ]
