# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0005_student_nominator'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityService',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('organizations', models.CharField(default='null', max_length=500)),
                ('service_hours', models.IntegerField(default=0)),
                ('service_hour_proof', models.CharField(default='null', max_length=500)),
                ('honors_awards', models.CharField(default='null', max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='academics',
            name='act_english',
        ),
        migrations.RemoveField(
            model_name='academics',
            name='act_math',
        ),
        migrations.RemoveField(
            model_name='academics',
            name='act_reading',
        ),
        migrations.RemoveField(
            model_name='academics',
            name='act_science',
        ),
        migrations.RemoveField(
            model_name='academics',
            name='act_writing',
        ),
        migrations.RemoveField(
            model_name='academics',
            name='sat_math',
        ),
        migrations.RemoveField(
            model_name='academics',
            name='sat_reading',
        ),
        migrations.RemoveField(
            model_name='academics',
            name='sat_writing',
        ),
        migrations.AddField(
            model_name='academics',
            name='academic_awards',
            field=models.CharField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='academics',
            name='number_ap_classes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='academics',
            name='organizations',
            field=models.CharField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='art',
            name='file_upload',
            field=models.CharField(default='null', max_length=300),
        ),
        migrations.AddField(
            model_name='art',
            name='honors_awards',
            field=models.CharField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='art',
            name='organizations',
            field=models.CharField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='art',
            name='portfolio_link',
            field=models.CharField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='stem',
            name='academic_achievement',
            field=models.CharField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='stem',
            name='honors_awards',
            field=models.CharField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='stem',
            name='leadership',
            field=models.CharField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='stem',
            name='organizations',
            field=models.CharField(default='null', max_length=500),
        ),
    ]
