# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0006_auto_20171104_0817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Athletics',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('organizations', models.CharField(default='null', max_length=500)),
                ('honors_awards', models.CharField(default='null', max_length=500)),
                ('leadership', models.CharField(default='null', max_length=500)),
                ('academic_achievement', models.CharField(default='null', max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='stem',
            name='academic_achievement',
        ),
        migrations.RemoveField(
            model_name='stem',
            name='leadership',
        ),
        migrations.AddField(
            model_name='stem',
            name='coursework',
            field=models.CharField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='stem',
            name='projects',
            field=models.CharField(default='null', max_length=500),
        ),
    ]
