# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0007_auto_20171104_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='academics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='overall',
            field=models.BooleanField(default=False),
        ),
    ]
